### ISSUE TITLE
DNS bug

### ISSUE THREAD

**Issue by nabeh** [rehmatworks/serverpilot-letsencrypt#44]
When i try to install ssl with the new script i get this error:
`A possible DNS issue found. domain.com may be pointing to a wrong IP ()`
what might be the issue? it was working perfectly before.

**Comment by lqdforce** [comment]
same thing, happens with renewal and re-issue, also happens with new domains.
tried everything DNS-related, it's something about the dns check of `socket.gethostbyname(domain)`
more specifically, in call to `validators.ipv4` or `validdoms`

@rehmatworks are you still maintaining this? any chance for a logger or a verbose mode, even a more informative error?

**Comment by rrrevin** [comment]
I have the exact same issue. I thought the issue might be that the domain is a CNAME, so I changed it to an A record. The IP is correct. Same error.
```
# rwssl getcert --app testapp
Do you really want to obtain an SSL certificate for the app testapp? [Y/N] y
Activating SSL for app testapp...
A possible DNS issue found. new.XXXXX.com may be pointing to a wrong IP (N.N.N.N)
SSL not available for this app yet.
```

**Comment by rrrevin** [comment]
For those who cannot wait for a fix.. I used the following info here to get an SSL for ServerPilot..
https://www.robertwent.com/blog/using-letsencrypt-serverpilot/

**Comment by TSerra-PT** [comment]
For thoses who are facing this issue/problem, uninstall this rwssl version (through this command pip3 uninstall rwssl) and install the previous version.
This is a link to the old version [https://web.archive.org/web/20191014061919/https://github.com/rehmatworks/serverpilot-letsencrypt](https://web.archive.org/web/20191014061919/https://github.com/rehmatworks/serverpilot-letsencrypt).

It is a temporary solution, but it is a solution.
I had this "DNS bug", but now (through the old version) i could install the new ssl's certificates in my app's

**Comment by rehmatworks** [comment]
I've pushed the fix, please install the latest version:

```bash
pip install rwssl==2.0.1
```
I hope this fixes all issues.

**Comment by lqdforce** [comment]
@rehmatworks updated to 2.0.4 to test this.
still getting the same error.

i could try a clean install but wanted to troubleshoot.
anything I can do to provide more info?

**Comment by rehmatworks** [comment]
@lqdforce If your server is from the old grandfathered plan, is this possible for you to provide me the root access? I don't have a grandfathered server to test against. If that's possible, please send me an email at contact[at]rehmat.works

**Comment by vntechsolutions** [comment]
I got the same issue with a grandfathered server.

**Comment by Bronskiy** [comment]
Same issue too.  grandfathered server.
